server:
  port: 8079


spring:
  jpa:
    database-platform: com.practice.scheduler.config.SQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:sqlite:scheduler.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

